import './blur.test';
import './click.test';
import './double-click.test';
// import './fill-in.test';
// import './find-all.test';
// import './find.test';
// import './focus.test';
// import './scroll-to.test';
// import './select-files.test';
// import './select.test';
// import './settled.test';
// import './tap.test';
// import './trigger-event.test';
// import './trigger-key-event.test';
// import './type-in.test';
// import './wait-for.test';
// import './wait-until.test';
